/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Conta;
import model.Endereco;
import model.Evento;
import model.Funcionario;
import model.Gasto;
import model.Gestor;
import model.Voluntario;
import model.VoluntarioPF;
import model.VoluntarioPJ;

/**
 *
 * @author lucas
 */
public class MoraisVoluntariado extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
	boolean connected = false;
	private Funcionario userFuncionario;
	private Gestor userGestor;
	private VoluntarioPF userVolPF;
	private VoluntarioPJ userVolPJ;
	private int userId;
	private int idCount = 1;
	private ArrayList<Conta> listaContas = new ArrayList<Conta>();
	private ArrayList<Funcionario> listaFuncionarios = new ArrayList<Funcionario>();
	private ArrayList<Gestor> listaGestores = new ArrayList<Gestor>();
	private ArrayList<Voluntario> listaVoluntarios = new ArrayList<Voluntario>();
	private ArrayList<Gasto> listaGastosTemp = new ArrayList<Gasto>();
	private ArrayList<Evento> listaEventos = new ArrayList<Evento>();
	
    public MoraisVoluntariado() {
        initComponents();
		resetLayers();
		loginPanel.setVisible(true);
		
		listaContas.add(new Conta(0, "lucaslins", "88219442", "Funcionário"));
		listaFuncionarios.add(new Funcionario(0, "Lucas Lins", "Masculino", "123456789", "88219442", null));
		listaFuncionarios.add(new Funcionario(1, "Alana Marques", "Feminino", "123456789", "88219442", null));
    }
	
	public void resetLayers(){
		loginPanel.setVisible(false);
		pnFuncionario.setVisible(false);
		pnFuncMain.setVisible(false);
		pnCdVolPF.setVisible(false);
		pnCdVolPJ.setVisible(false);
		pnCdEvento.setVisible(false);
	}
	
	public void enableFuncionario(){
		pnFuncMain.setVisible(true); // Paginá principal Funcionário
		pnFuncionario.setVisible(true); // Menu Funcionário
		taInfoFuncionario.setText(userFuncionario.toString());
	}
	
	public void clearCdVolPF(){
		tfVolPFNome.setText("");
		tfVolPFBairro.setText("");
		tfVolPFCidade.setText("");
		tfVolPFComplemento.setText("");
		tfVolPFNumero.setText("");
		tfVolPFRua.setText("");
		ftfVolPFCEP.setText("");
		ftfVolPFCPF.setText("");
		ftfVolPFTelefone.setText("");
	}
	
	public void clearCdVolPJ(){
		tfVolPJNome.setText("");
		tfVolPJBairro.setText("");
		tfVolPJCidade.setText("");
		tfVolPJComplemento.setText("");
		tfVolPJNumero.setText("");
		tfVolPJRua.setText("");
		ftfVolPJCEP.setText("");
		ftfVolPJCNPJ.setText("");
		ftfVolPJIE.setText("");
		ftfVolPJTelefone.setText("");
	}
	
	public void clearCdEvento(){
		tfNomeEvento.setText("");
		tfNomeGasto.setText("");
		tfValorGasto.setText("");
		ftfDataEvento.setText("");
		ftfDuracaoFim.setText("");
		ftfDuracaoInicio.setText("");
		tpObjetivoEvento.setText("");
		listaGastosTemp.clear();
		jLGastos.setModel(converterGastosLista());
	}
	
	public DefaultListModel<String> converterFuncionariosLista(){
		DefaultListModel<String> listModel = new DefaultListModel<String>();
		for(int i = 0; i<listaFuncionarios.size(); i++){
			listModel.addElement(listaFuncionarios.get(i).getNome());
		}
		return listModel;
	}
	
	public DefaultListModel<String> converterGastosLista(){
		DefaultListModel<String> listModel = new DefaultListModel<String>();
		for(int i = 0; i<listaGastosTemp.size(); i++){
			listModel.addElement(listaGastosTemp.get(i).toString());
		}
		return listModel;
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLogin5 = new keeptoo.KButton();
        loginPanel = new keeptoo.KGradientPanel();
        tfLogin = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        btLogin = new keeptoo.KButton();
        iconMV = new javax.swing.JLabel();
        ldMenus = new javax.swing.JLayeredPane();
        pnFuncionario = new keeptoo.KGradientPanel();
        lbTituloFuncionario = new javax.swing.JLabel();
        btEntregas = new keeptoo.KButton();
        btCadastroVoluntario = new keeptoo.KButton();
        btFuncInicio = new keeptoo.KButton();
        btCadastroEvento = new keeptoo.KButton();
        btCadastroTrabalho = new keeptoo.KButton();
        btAceitarDoacao = new keeptoo.KButton();
        btRemoverVoluntario = new keeptoo.KButton();
        btRelatorios = new keeptoo.KButton();
        btImportarDados = new keeptoo.KButton();
        btFuncLogout1 = new keeptoo.KButton();
        ldFuncionario = new javax.swing.JLayeredPane();
        pnFuncMain = new javax.swing.JPanel();
        pnMainTitle = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInfoFuncionario = new javax.swing.JTextArea();
        pnCdVolPF = new javax.swing.JPanel();
        pnCdVolTitle = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        pnDados = new javax.swing.JPanel();
        ftfVolPFTelefone = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        tfVolPFNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftfVolPFCPF = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cbVolPFSexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbVolPFTurno = new javax.swing.JComboBox<>();
        btCadastrarVolPF = new keeptoo.KButton();
        pnEndereco = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfVolPFRua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfVolPFNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfVolPFComplemento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfVolPFBairro = new javax.swing.JTextField();
        tfVolPFCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbVolPFUF = new javax.swing.JComboBox<>();
        ftfVolPFCEP = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfVolPFUsuario = new javax.swing.JTextField();
        tfVolPFSenha = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnCdVolPJ = new javax.swing.JPanel();
        pnCdVolTitle1 = new keeptoo.KGradientPanel();
        jLabel19 = new javax.swing.JLabel();
        pnDados1 = new javax.swing.JPanel();
        ftfVolPJTelefone = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        tfVolPJNome = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ftfVolPJCNPJ = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        ftfVolPJIE = new javax.swing.JFormattedTextField();
        btCadastrarVolPJ = new keeptoo.KButton();
        pnEndereco1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        tfVolPJRua = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfVolPJNumero = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tfVolPJComplemento = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tfVolPJBairro = new javax.swing.JTextField();
        tfVolPJCidade = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cbVolPJUF = new javax.swing.JComboBox<>();
        ftfVolPJCEP = new javax.swing.JFormattedTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tfVolPJUsuario = new javax.swing.JTextField();
        tfVolPJSenha = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        pnCdEvento = new javax.swing.JPanel();
        pnMainTitle1 = new keeptoo.KGradientPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tfNomeEvento = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        ftfDataEvento = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpObjetivoEvento = new javax.swing.JTextPane();
        jLabel40 = new javax.swing.JLabel();
        ftfDuracaoInicio = new javax.swing.JFormattedTextField();
        ftfDuracaoFim = new javax.swing.JFormattedTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLGastos = new javax.swing.JList<>();
        jLabel42 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jLFuncionarios = new javax.swing.JList<>();
        btInfoFuncionario = new keeptoo.KButton();
        btAddGasto = new keeptoo.KButton();
        tfNomeGasto = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        btRemoveGasto = new keeptoo.KButton();
        tfValorGasto = new javax.swing.JTextField();
        btCadastrarEvento = new keeptoo.KButton();

        btLogin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/new work.png"))); // NOI18N
        btLogin5.setText("Cadastrar Trabalho");
        btLogin5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLogin5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLogin5.setIconTextGap(0);
        btLogin5.setkBorderRadius(0);
        btLogin5.setkEndColor(new java.awt.Color(233, 193, 253));
        btLogin5.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btLogin5.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btLogin5.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btLogin5.setkPressedColor(new java.awt.Color(250, 209, 254));
        btLogin5.setkStartColor(new java.awt.Color(199, 96, 230));
        btLogin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Morais Voluntariado");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setkEndColor(new java.awt.Color(51, 0, 102));
        loginPanel.setkGradientFocus(90);
        loginPanel.setkStartColor(new java.awt.Color(54, 33, 89));
        loginPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        loginPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        loginPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfLogin.setBackground(new Color(0,0,0,0));
        tfLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfLogin.setForeground(new java.awt.Color(255, 255, 255));
        tfLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        tfLogin.setCaretColor(new java.awt.Color(255, 255, 255));
        tfLogin.setOpaque(false);
        tfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoginActionPerformed(evt);
            }
        });
        loginPanel.add(tfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 242, 200, 30));

        pfSenha.setBackground(new Color(0,0,0,0));
        pfSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfSenha.setForeground(new java.awt.Color(255, 255, 255));
        pfSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pfSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pfSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        pfSenha.setOpaque(false);
        pfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaActionPerformed(evt);
            }
        });
        loginPanel.add(pfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 316, 200, 30));

        lbLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbLogin.setText("Login");
        loginPanel.add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 212, -1, -1));

        lbSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbSenha.setText("Senha");
        loginPanel.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        btLogin.setText("Entrar");
        btLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btLogin.setkEndColor(new java.awt.Color(233, 193, 253));
        btLogin.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btLogin.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btLogin.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btLogin.setkPressedColor(new java.awt.Color(250, 209, 254));
        btLogin.setkStartColor(new java.awt.Color(199, 96, 230));
        loginPanel.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 364, 112, 32));

        iconMV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logotext.png"))); // NOI18N
        loginPanel.add(iconMV, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 11, -1, -1));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ldMenus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnFuncionario.setkBorderRadius(0);
        pnFuncionario.setkEndColor(new java.awt.Color(102, 0, 102));
        pnFuncionario.setkStartColor(new java.awt.Color(51, 0, 102));
        pnFuncionario.setPreferredSize(new java.awt.Dimension(160, 500));
        pnFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloFuncionario.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lbTituloFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloFuncionario.setText("Funcionário");
        pnFuncionario.add(lbTituloFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/delivery.png"))); // NOI18N
        btEntregas.setText("Gerenciar Entregas");
        btEntregas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEntregas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEntregas.setIconTextGap(0);
        btEntregas.setkBorderRadius(0);
        btEntregas.setkEndColor(new java.awt.Color(233, 193, 253));
        btEntregas.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btEntregas.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btEntregas.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btEntregas.setkPressedColor(new java.awt.Color(250, 209, 254));
        btEntregas.setkStartColor(new java.awt.Color(199, 96, 230));
        btEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntregasActionPerformed(evt);
            }
        });
        pnFuncionario.add(btEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 160, 40));

        btCadastroVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/addfuncionario.png"))); // NOI18N
        btCadastroVoluntario.setText("Cadastrar Voluntário");
        btCadastroVoluntario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastroVoluntario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastroVoluntario.setIconTextGap(1);
        btCadastroVoluntario.setkBorderRadius(0);
        btCadastroVoluntario.setkEndColor(new java.awt.Color(233, 193, 253));
        btCadastroVoluntario.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btCadastroVoluntario.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btCadastroVoluntario.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btCadastroVoluntario.setkPressedColor(new java.awt.Color(250, 209, 254));
        btCadastroVoluntario.setkStartColor(new java.awt.Color(199, 96, 230));
        btCadastroVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroVoluntarioActionPerformed(evt);
            }
        });
        pnFuncionario.add(btCadastroVoluntario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 40));

        btFuncInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/home.png"))); // NOI18N
        btFuncInicio.setText("Início");
        btFuncInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFuncInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFuncInicio.setIconTextGap(0);
        btFuncInicio.setkBorderRadius(0);
        btFuncInicio.setkEndColor(new java.awt.Color(233, 193, 253));
        btFuncInicio.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btFuncInicio.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btFuncInicio.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btFuncInicio.setkPressedColor(new java.awt.Color(250, 209, 254));
        btFuncInicio.setkStartColor(new java.awt.Color(199, 96, 230));
        btFuncInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncInicioActionPerformed(evt);
            }
        });
        pnFuncionario.add(btFuncInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        btCadastroEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/new event.png"))); // NOI18N
        btCadastroEvento.setText("Cadastrar Evento");
        btCadastroEvento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastroEvento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastroEvento.setIconTextGap(0);
        btCadastroEvento.setkBorderRadius(0);
        btCadastroEvento.setkEndColor(new java.awt.Color(233, 193, 253));
        btCadastroEvento.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btCadastroEvento.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btCadastroEvento.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btCadastroEvento.setkPressedColor(new java.awt.Color(250, 209, 254));
        btCadastroEvento.setkStartColor(new java.awt.Color(199, 96, 230));
        btCadastroEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroEventoActionPerformed(evt);
            }
        });
        pnFuncionario.add(btCadastroEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 40));

        btCadastroTrabalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/new work.png"))); // NOI18N
        btCadastroTrabalho.setText("Cadastrar Trabalho");
        btCadastroTrabalho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastroTrabalho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastroTrabalho.setIconTextGap(0);
        btCadastroTrabalho.setkBorderRadius(0);
        btCadastroTrabalho.setkEndColor(new java.awt.Color(233, 193, 253));
        btCadastroTrabalho.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btCadastroTrabalho.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btCadastroTrabalho.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btCadastroTrabalho.setkPressedColor(new java.awt.Color(250, 209, 254));
        btCadastroTrabalho.setkStartColor(new java.awt.Color(199, 96, 230));
        btCadastroTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroTrabalhoActionPerformed(evt);
            }
        });
        pnFuncionario.add(btCadastroTrabalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 40));

        btAceitarDoacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/donate.png"))); // NOI18N
        btAceitarDoacao.setText("Aceitar Doações");
        btAceitarDoacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAceitarDoacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAceitarDoacao.setIconTextGap(0);
        btAceitarDoacao.setkBorderRadius(0);
        btAceitarDoacao.setkEndColor(new java.awt.Color(233, 193, 253));
        btAceitarDoacao.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btAceitarDoacao.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btAceitarDoacao.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btAceitarDoacao.setkPressedColor(new java.awt.Color(250, 209, 254));
        btAceitarDoacao.setkStartColor(new java.awt.Color(199, 96, 230));
        btAceitarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceitarDoacaoActionPerformed(evt);
            }
        });
        pnFuncionario.add(btAceitarDoacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 160, 40));

        btRemoverVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/removefuncionario.png"))); // NOI18N
        btRemoverVoluntario.setText("Remover Volutário");
        btRemoverVoluntario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btRemoverVoluntario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRemoverVoluntario.setIconTextGap(0);
        btRemoverVoluntario.setkBorderRadius(0);
        btRemoverVoluntario.setkEndColor(new java.awt.Color(233, 193, 253));
        btRemoverVoluntario.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btRemoverVoluntario.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btRemoverVoluntario.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btRemoverVoluntario.setkPressedColor(new java.awt.Color(250, 209, 254));
        btRemoverVoluntario.setkStartColor(new java.awt.Color(199, 96, 230));
        btRemoverVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverVoluntarioActionPerformed(evt);
            }
        });
        pnFuncionario.add(btRemoverVoluntario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 160, 40));

        btRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/archive.png"))); // NOI18N
        btRelatorios.setText("Relatórios");
        btRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRelatorios.setIconTextGap(0);
        btRelatorios.setkBorderRadius(0);
        btRelatorios.setkEndColor(new java.awt.Color(233, 193, 253));
        btRelatorios.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btRelatorios.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btRelatorios.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btRelatorios.setkPressedColor(new java.awt.Color(250, 209, 254));
        btRelatorios.setkStartColor(new java.awt.Color(199, 96, 230));
        btRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatoriosActionPerformed(evt);
            }
        });
        pnFuncionario.add(btRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 160, 40));

        btImportarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/import.png"))); // NOI18N
        btImportarDados.setText("Importar Dados");
        btImportarDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btImportarDados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImportarDados.setIconTextGap(0);
        btImportarDados.setkBorderRadius(0);
        btImportarDados.setkEndColor(new java.awt.Color(233, 193, 253));
        btImportarDados.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btImportarDados.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btImportarDados.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btImportarDados.setkPressedColor(new java.awt.Color(250, 209, 254));
        btImportarDados.setkStartColor(new java.awt.Color(199, 96, 230));
        btImportarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImportarDadosActionPerformed(evt);
            }
        });
        pnFuncionario.add(btImportarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 160, 40));

        btFuncLogout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/exit.png"))); // NOI18N
        btFuncLogout1.setText("Desconectar");
        btFuncLogout1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFuncLogout1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFuncLogout1.setIconTextGap(0);
        btFuncLogout1.setkBorderRadius(0);
        btFuncLogout1.setkEndColor(new java.awt.Color(233, 193, 253));
        btFuncLogout1.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btFuncLogout1.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btFuncLogout1.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btFuncLogout1.setkPressedColor(new java.awt.Color(250, 209, 254));
        btFuncLogout1.setkStartColor(new java.awt.Color(199, 96, 230));
        btFuncLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncLogout1ActionPerformed(evt);
            }
        });
        pnFuncionario.add(btFuncLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 160, 40));

        ldMenus.add(pnFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(ldMenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 500));

        ldFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnFuncMain.setBackground(new java.awt.Color(204, 204, 204));
        pnFuncMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMainTitle.setkBorderRadius(0);
        pnMainTitle.setkEndColor(new java.awt.Color(204, 0, 204));
        pnMainTitle.setkStartColor(new java.awt.Color(51, 0, 102));
        pnMainTitle.setPreferredSize(new java.awt.Dimension(640, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Início");

        javax.swing.GroupLayout pnMainTitleLayout = new javax.swing.GroupLayout(pnMainTitle);
        pnMainTitle.setLayout(pnMainTitleLayout);
        pnMainTitleLayout.setHorizontalGroup(
            pnMainTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainTitleLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel2)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        pnMainTitleLayout.setVerticalGroup(
            pnMainTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pnFuncMain.add(pnMainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seus dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        taInfoFuncionario.setEditable(false);
        taInfoFuncionario.setColumns(20);
        taInfoFuncionario.setRows(5);
        jScrollPane1.setViewportView(taInfoFuncionario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 214, Short.MAX_VALUE))
        );

        pnFuncMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 620, 440));

        ldFuncionario.add(pnFuncMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pnCdVolPF.setBackground(new java.awt.Color(204, 204, 204));
        pnCdVolPF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnCdVolTitle.setkBorderRadius(0);
        pnCdVolTitle.setkEndColor(new java.awt.Color(204, 0, 204));
        pnCdVolTitle.setkStartColor(new java.awt.Color(51, 0, 102));
        pnCdVolTitle.setPreferredSize(new java.awt.Dimension(640, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Voluntário");

        javax.swing.GroupLayout pnCdVolTitleLayout = new javax.swing.GroupLayout(pnCdVolTitle);
        pnCdVolTitle.setLayout(pnCdVolTitleLayout);
        pnCdVolTitleLayout.setHorizontalGroup(
            pnCdVolTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCdVolTitleLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        pnCdVolTitleLayout.setVerticalGroup(
            pnCdVolTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCdVolTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnCdVolPF.add(pnCdVolTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        pnDados.setBackground(new java.awt.Color(204, 204, 204));
        pnDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(102, 0, 102)));

        try {
            ftfVolPFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Nome");

        jLabel4.setText("Telefone");

        jLabel5.setText("CPF");

        try {
            ftfVolPFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Sexo");

        cbVolPFSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        jLabel7.setText("Turno");

        cbVolPFTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));

        javax.swing.GroupLayout pnDadosLayout = new javax.swing.GroupLayout(pnDados);
        pnDados.setLayout(pnDadosLayout);
        pnDadosLayout.setHorizontalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(tfVolPFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(ftfVolPFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(ftfVolPFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addComponent(cbVolPFSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(cbVolPFTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnDadosLayout.setVerticalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(tfVolPFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(ftfVolPFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(ftfVolPFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(cbVolPFSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(cbVolPFTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pnCdVolPF.add(pnDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 168, 250));

        btCadastrarVolPF.setText("Cadastrar");
        btCadastrarVolPF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btCadastrarVolPF.setkEndColor(new java.awt.Color(233, 193, 253));
        btCadastrarVolPF.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btCadastrarVolPF.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btCadastrarVolPF.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btCadastrarVolPF.setkPressedColor(new java.awt.Color(250, 209, 254));
        btCadastrarVolPF.setkStartColor(new java.awt.Color(199, 96, 230));
        btCadastrarVolPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarVolPFActionPerformed(evt);
            }
        });
        pnCdVolPF.add(btCadastrarVolPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 110, 30));

        pnEndereco.setBackground(new java.awt.Color(204, 204, 204));
        pnEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(102, 0, 102)));

        jLabel8.setText("Rua");

        jLabel9.setText("Número");

        jLabel10.setText("Complemento");

        jLabel11.setText("Bairro");

        jLabel12.setText("Cidade");

        jLabel13.setText("UF");

        jLabel14.setText("CEP");

        cbVolPFUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            ftfVolPFCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnEnderecoLayout = new javax.swing.GroupLayout(pnEndereco);
        pnEndereco.setLayout(pnEnderecoLayout);
        pnEnderecoLayout.setHorizontalGroup(
            pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEnderecoLayout.createSequentialGroup()
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfVolPFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfVolPFRua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfVolPFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfVolPFComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEnderecoLayout.createSequentialGroup()
                        .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfVolPFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfVolPFNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbVolPFUF, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        pnEnderecoLayout.setVerticalGroup(
            pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEnderecoLayout.createSequentialGroup()
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(tfVolPFRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(tfVolPFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(tfVolPFComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVolPFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfVolPFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVolPFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVolPFUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnCdVolPF.add(pnEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 200, 250));

        jLabel15.setText("Endereço");
        pnCdVolPF.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 46, -1, -1));

        jLabel16.setText("Dados");
        pnCdVolPF.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 44, -1, 20));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(102, 0, 102)));

        jLabel17.setText("Usuário");

        jLabel18.setText("Senha");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfVolPFUsuario)
                    .addComponent(tfVolPFSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfVolPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfVolPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pnCdVolPF.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 190, 250));

        jLabel20.setText("Conta");
        pnCdVolPF.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 44, -1, 20));

        ldFuncionario.add(pnCdVolPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pnCdVolPJ.setBackground(new java.awt.Color(204, 204, 204));
        pnCdVolPJ.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnCdVolTitle1.setkBorderRadius(0);
        pnCdVolTitle1.setkEndColor(new java.awt.Color(204, 0, 204));
        pnCdVolTitle1.setkStartColor(new java.awt.Color(51, 0, 102));
        pnCdVolTitle1.setPreferredSize(new java.awt.Dimension(640, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cadastrar Voluntário");

        javax.swing.GroupLayout pnCdVolTitle1Layout = new javax.swing.GroupLayout(pnCdVolTitle1);
        pnCdVolTitle1.setLayout(pnCdVolTitle1Layout);
        pnCdVolTitle1Layout.setHorizontalGroup(
            pnCdVolTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCdVolTitle1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel19)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        pnCdVolTitle1Layout.setVerticalGroup(
            pnCdVolTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCdVolTitle1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnCdVolPJ.add(pnCdVolTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        pnDados1.setBackground(new java.awt.Color(204, 204, 204));
        pnDados1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(102, 0, 102)));

        try {
            ftfVolPJTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel21.setText("Nome Fantasia");

        jLabel22.setText("Telefone");

        jLabel23.setText("CNPJ");

        try {
            ftfVolPJCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel24.setText("Inscrição Estadual");

        try {
            ftfVolPJIE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnDados1Layout = new javax.swing.GroupLayout(pnDados1);
        pnDados1.setLayout(pnDados1Layout);
        pnDados1Layout.setHorizontalGroup(
            pnDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDados1Layout.createSequentialGroup()
                .addGroup(pnDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDados1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfVolPJIE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDados1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDados1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfVolPJCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDados1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfVolPJTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDados1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfVolPJNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnDados1Layout.setVerticalGroup(
            pnDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDados1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pnDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfVolPJNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfVolPJTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(6, 6, 6)
                .addGroup(pnDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ftfVolPJCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfVolPJIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pnCdVolPJ.add(pnDados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 220, 250));

        btCadastrarVolPJ.setText("Cadastrar");
        btCadastrarVolPJ.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btCadastrarVolPJ.setkEndColor(new java.awt.Color(233, 193, 253));
        btCadastrarVolPJ.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btCadastrarVolPJ.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btCadastrarVolPJ.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btCadastrarVolPJ.setkPressedColor(new java.awt.Color(250, 209, 254));
        btCadastrarVolPJ.setkStartColor(new java.awt.Color(199, 96, 230));
        btCadastrarVolPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarVolPJActionPerformed(evt);
            }
        });
        pnCdVolPJ.add(btCadastrarVolPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 110, 30));

        pnEndereco1.setBackground(new java.awt.Color(204, 204, 204));
        pnEndereco1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(102, 0, 102)));

        jLabel26.setText("Rua");

        jLabel27.setText("Número");

        jLabel28.setText("Complemento");

        jLabel29.setText("Bairro");

        jLabel30.setText("Cidade");

        jLabel31.setText("UF");

        jLabel32.setText("CEP");

        cbVolPJUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            ftfVolPJCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnEndereco1Layout = new javax.swing.GroupLayout(pnEndereco1);
        pnEndereco1.setLayout(pnEndereco1Layout);
        pnEndereco1Layout.setHorizontalGroup(
            pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEndereco1Layout.createSequentialGroup()
                .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnEndereco1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfVolPJBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEndereco1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfVolPJRua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEndereco1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfVolPJCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEndereco1Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfVolPJComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEndereco1Layout.createSequentialGroup()
                        .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel27)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfVolPJCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfVolPJNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbVolPJUF, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        pnEndereco1Layout.setVerticalGroup(
            pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEndereco1Layout.createSequentialGroup()
                .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel26)
                    .addComponent(tfVolPJRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel29)
                    .addComponent(tfVolPJBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel28)
                    .addComponent(tfVolPJComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVolPJCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfVolPJCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVolPJNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVolPJUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pnCdVolPJ.add(pnEndereco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 200, 250));

        jLabel33.setText("Endereço");
        pnCdVolPJ.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, 20));

        jLabel34.setText("Dados");
        pnCdVolPJ.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, 20));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(102, 0, 102)));

        jLabel35.setText("Usuário");

        jLabel36.setText("Senha");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfVolPJUsuario)
                    .addComponent(tfVolPJSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tfVolPJUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(tfVolPJSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pnCdVolPJ.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 170, 250));

        jLabel37.setText("Conta");
        pnCdVolPJ.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, 20));

        ldFuncionario.add(pnCdVolPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pnCdEvento.setBackground(new java.awt.Color(204, 204, 204));
        pnCdEvento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMainTitle1.setkBorderRadius(0);
        pnMainTitle1.setkEndColor(new java.awt.Color(204, 0, 204));
        pnMainTitle1.setkStartColor(new java.awt.Color(51, 0, 102));
        pnMainTitle1.setPreferredSize(new java.awt.Dimension(640, 40));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Cadastrar Evento");

        javax.swing.GroupLayout pnMainTitle1Layout = new javax.swing.GroupLayout(pnMainTitle1);
        pnMainTitle1.setLayout(pnMainTitle1Layout);
        pnMainTitle1Layout.setHorizontalGroup(
            pnMainTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainTitle1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(244, 244, 244))
        );
        pnMainTitle1Layout.setVerticalGroup(
            pnMainTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainTitle1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnCdEvento.add(pnMainTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 40));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(102, 0, 102)));

        jLabel38.setText("Nome");

        jLabel39.setText("Data");

        try {
            ftfDataEvento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jScrollPane2.setViewportView(tpObjetivoEvento);

        jLabel40.setText("Objetivo");

        try {
            ftfDuracaoInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDuracaoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfDuracaoInicioActionPerformed(evt);
            }
        });

        try {
            ftfDuracaoFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel41.setText("Duração");

        jLabel44.setText("    Início    –      Fim");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel38)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNomeEvento)
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ftfDuracaoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfDuracaoFim))
                    .addComponent(ftfDataEvento))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(ftfDataEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(ftfDuracaoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfDuracaoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel44)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pnCdEvento.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 410, 140));

        jLabel43.setText("Dados");
        pnCdEvento.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 44, -1, 20));

        jLGastos.setModel(converterFuncionariosLista());
        jScrollPane3.setViewportView(jLGastos);

        pnCdEvento.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 410, 110));

        jLabel42.setText("Selecionar funcionário responsável");
        pnCdEvento.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 204, -1, 20));

        jLabel45.setText("Gastos");
        pnCdEvento.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, 20));

        jLFuncionarios.setModel(converterFuncionariosLista());
        jScrollPane5.setViewportView(jLFuncionarios);

        pnCdEvento.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 410, 80));

        btInfoFuncionario.setText("Ver informações");
        btInfoFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btInfoFuncionario.setkEndColor(new java.awt.Color(233, 193, 253));
        btInfoFuncionario.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btInfoFuncionario.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btInfoFuncionario.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btInfoFuncionario.setkPressedColor(new java.awt.Color(250, 209, 254));
        btInfoFuncionario.setkStartColor(new java.awt.Color(199, 96, 230));
        btInfoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInfoFuncionarioActionPerformed(evt);
            }
        });
        pnCdEvento.add(btInfoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 100, 20));

        btAddGasto.setText("Adicionar");
        btAddGasto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btAddGasto.setkEndColor(new java.awt.Color(233, 193, 253));
        btAddGasto.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btAddGasto.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btAddGasto.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btAddGasto.setkPressedColor(new java.awt.Color(250, 209, 254));
        btAddGasto.setkStartColor(new java.awt.Color(199, 96, 230));
        btAddGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddGastoActionPerformed(evt);
            }
        });
        pnCdEvento.add(btAddGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 60, 20));
        pnCdEvento.add(tfNomeGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 130, -1));

        jLabel46.setText("Descrição");
        pnCdEvento.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 60, 20));

        jLabel47.setText("Valor");
        pnCdEvento.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, 20));

        btRemoveGasto.setText("Remover item");
        btRemoveGasto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btRemoveGasto.setkEndColor(new java.awt.Color(233, 193, 253));
        btRemoveGasto.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btRemoveGasto.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btRemoveGasto.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btRemoveGasto.setkPressedColor(new java.awt.Color(250, 209, 254));
        btRemoveGasto.setkStartColor(new java.awt.Color(199, 96, 230));
        btRemoveGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveGastoActionPerformed(evt);
            }
        });
        pnCdEvento.add(btRemoveGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 80, 20));
        pnCdEvento.add(tfValorGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 110, -1));

        btCadastrarEvento.setText("Cadastrar Evento");
        btCadastrarEvento.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btCadastrarEvento.setkEndColor(new java.awt.Color(233, 193, 253));
        btCadastrarEvento.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btCadastrarEvento.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btCadastrarEvento.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btCadastrarEvento.setkPressedColor(new java.awt.Color(250, 209, 254));
        btCadastrarEvento.setkStartColor(new java.awt.Color(199, 96, 230));
        btCadastrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarEventoActionPerformed(evt);
            }
        });
        pnCdEvento.add(btCadastrarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 100, 50));

        ldFuncionario.add(pnCdEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(ldFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoginActionPerformed

    private void btEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntregasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEntregasActionPerformed

    private void btCadastroVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroVoluntarioActionPerformed
       Object[] tipoVol = {"Pessoa Física", "Pessoa Jurídica"};
	   Object choice = JOptionPane.showOptionDialog(rootPane, "Qual tipo de voluntário deseja cadastrar?", "Cadastrar Voluntário", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, tipoVol, tipoVol);
	   if(choice.toString().equals("0")){
		   resetLayers();
		   pnFuncionario.setVisible(true);
		   pnCdVolPF.setVisible(true);
	   }
	   else if(choice.toString().equals("1")){
		   resetLayers();
		   pnFuncionario.setVisible(true);
		   pnCdVolPJ.setVisible(true);
	   }
    }//GEN-LAST:event_btCadastroVoluntarioActionPerformed

    private void btFuncInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncInicioActionPerformed
        resetLayers();
		enableFuncionario();
    }//GEN-LAST:event_btFuncInicioActionPerformed

    private void btCadastroEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroEventoActionPerformed
        resetLayers();
		pnFuncionario.setVisible(true);
		pnCdEvento.setVisible(true);
		jLFuncionarios.setModel(converterFuncionariosLista());
    }//GEN-LAST:event_btCadastroEventoActionPerformed

    private void btLogin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogin5ActionPerformed

    private void btCadastroTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastroTrabalhoActionPerformed

    private void btAceitarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceitarDoacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAceitarDoacaoActionPerformed

    private void btRemoverVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverVoluntarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRemoverVoluntarioActionPerformed

    private void btRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRelatoriosActionPerformed

    private void btImportarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImportarDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btImportarDadosActionPerformed

    private void pfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenhaActionPerformed

    private void btFuncLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncLogout1ActionPerformed
        Object[] botoesDesconectar = {"Desconectar", "Voltar"};
		Object choice = JOptionPane.showOptionDialog(rootPane, "Tem certeza que deseja sair?", "Desconectar", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, botoesDesconectar, botoesDesconectar);
		if(choice.toString().equals("0")){
			connected = false;
			userFuncionario = null;
			resetLayers();
			loginPanel.setVisible(true);
		}
    }//GEN-LAST:event_btFuncLogout1ActionPerformed

    private void btCadastrarVolPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarVolPFActionPerformed
        listaContas.add(new Conta(idCount, tfVolPFUsuario.getText(), tfVolPFSenha.getText(), "VoluntárioPF"));
		
		listaVoluntarios.add(new VoluntarioPF(idCount, tfVolPFNome.getText(), ftfVolPFTelefone.getText(), 
				new Endereco(tfVolPFRua.getText(), tfVolPFNumero.getText(), tfVolPFComplemento.getText(), 
				tfVolPFBairro.getText(), tfVolPFCidade.getText(), cbVolPFUF.getSelectedItem().toString(), 
				ftfVolPFCEP.getText()), ftfVolPFCPF.getText(), cbVolPFSexo.getSelectedItem().toString(), 
				cbVolPFTurno.getSelectedItem().toString()));
		JOptionPane.showMessageDialog(rootPane, "Voluntário cadastrado com sucesso!");
		idCount++;
		clearCdVolPF();
		resetLayers();
		enableFuncionario();
    }//GEN-LAST:event_btCadastrarVolPFActionPerformed

    private void btCadastrarVolPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarVolPJActionPerformed
        listaContas.add(new Conta(idCount, tfVolPJUsuario.getText(), tfVolPJSenha.getText(), "VoluntárioPJ"));
		
		listaVoluntarios.add(new VoluntarioPJ(idCount, tfVolPJNome.getText(), ftfVolPJTelefone.getText(), 
				new Endereco(tfVolPJRua.getText(), tfVolPJNumero.getText(), tfVolPJComplemento.getText(), 
				tfVolPJBairro.getText(), tfVolPJCidade.getText(), cbVolPJUF.getSelectedItem().toString(), 
				ftfVolPJCEP.getText()), ftfVolPJCNPJ.getText(), ftfVolPJIE.getText()));
		JOptionPane.showMessageDialog(rootPane, "Voluntário cadastrado com sucesso!");
		idCount++;
		clearCdVolPJ();
		resetLayers();
		enableFuncionario();
    }//GEN-LAST:event_btCadastrarVolPJActionPerformed

    private void ftfDuracaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfDuracaoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfDuracaoInicioActionPerformed

    private void btInfoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInfoFuncionarioActionPerformed
        JOptionPane.showMessageDialog(rootPane, listaFuncionarios.get(jLFuncionarios.getAnchorSelectionIndex()));
    }//GEN-LAST:event_btInfoFuncionarioActionPerformed

    private void btAddGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddGastoActionPerformed
        listaGastosTemp.add(new Gasto(tfNomeGasto.getText(), Double.parseDouble(tfValorGasto.getText())));
		jLGastos.setModel(converterGastosLista());
    }//GEN-LAST:event_btAddGastoActionPerformed

    private void btRemoveGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveGastoActionPerformed
        listaGastosTemp.remove(jLGastos.getAnchorSelectionIndex());
		jLGastos.setModel(converterGastosLista());
    }//GEN-LAST:event_btRemoveGastoActionPerformed

    private void btCadastrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarEventoActionPerformed
        listaEventos.add(new Evento(tfNomeEvento.getText(), ftfDataEvento.getText(), 
				String.format("%s – %s", ftfDuracaoInicio.getText(), ftfDuracaoFim.getText()), 
				tpObjetivoEvento.getText(), listaGastosTemp, listaFuncionarios.get(jLFuncionarios.getAnchorSelectionIndex())));
		clearCdEvento();
		resetLayers();
		enableFuncionario();
		JOptionPane.showMessageDialog(rootPane, "Evento cadastrado com sucesso!", "Cadastrar Evento", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btCadastrarEventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoraisVoluntariado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoraisVoluntariado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoraisVoluntariado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoraisVoluntariado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoraisVoluntariado().setVisible(true);
            }
        });
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btAceitarDoacao;
    private keeptoo.KButton btAddGasto;
    private keeptoo.KButton btCadastrarEvento;
    private keeptoo.KButton btCadastrarVolPF;
    private keeptoo.KButton btCadastrarVolPJ;
    private keeptoo.KButton btCadastroEvento;
    private keeptoo.KButton btCadastroTrabalho;
    private keeptoo.KButton btCadastroVoluntario;
    private keeptoo.KButton btEntregas;
    private keeptoo.KButton btFuncInicio;
    private keeptoo.KButton btFuncLogout1;
    private keeptoo.KButton btImportarDados;
    private keeptoo.KButton btInfoFuncionario;
    private keeptoo.KButton btLogin;
    private keeptoo.KButton btLogin5;
    private keeptoo.KButton btRelatorios;
    private keeptoo.KButton btRemoveGasto;
    private keeptoo.KButton btRemoverVoluntario;
    private javax.swing.JComboBox<String> cbVolPFSexo;
    private javax.swing.JComboBox<String> cbVolPFTurno;
    private javax.swing.JComboBox<String> cbVolPFUF;
    private javax.swing.JComboBox<String> cbVolPJUF;
    private javax.swing.JFormattedTextField ftfDataEvento;
    private javax.swing.JFormattedTextField ftfDuracaoFim;
    private javax.swing.JFormattedTextField ftfDuracaoInicio;
    private javax.swing.JFormattedTextField ftfVolPFCEP;
    private javax.swing.JFormattedTextField ftfVolPFCPF;
    private javax.swing.JFormattedTextField ftfVolPFTelefone;
    private javax.swing.JFormattedTextField ftfVolPJCEP;
    private javax.swing.JFormattedTextField ftfVolPJCNPJ;
    private javax.swing.JFormattedTextField ftfVolPJIE;
    private javax.swing.JFormattedTextField ftfVolPJTelefone;
    private javax.swing.JLabel iconMV;
    private javax.swing.JList<String> jLFuncionarios;
    private javax.swing.JList<String> jLGastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTituloFuncionario;
    private javax.swing.JLayeredPane ldFuncionario;
    private javax.swing.JLayeredPane ldMenus;
    private keeptoo.KGradientPanel loginPanel;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPanel pnCdEvento;
    private javax.swing.JPanel pnCdVolPF;
    private javax.swing.JPanel pnCdVolPJ;
    private keeptoo.KGradientPanel pnCdVolTitle;
    private keeptoo.KGradientPanel pnCdVolTitle1;
    private javax.swing.JPanel pnDados;
    private javax.swing.JPanel pnDados1;
    private javax.swing.JPanel pnEndereco;
    private javax.swing.JPanel pnEndereco1;
    private javax.swing.JPanel pnFuncMain;
    private keeptoo.KGradientPanel pnFuncionario;
    private keeptoo.KGradientPanel pnMainTitle;
    private keeptoo.KGradientPanel pnMainTitle1;
    private javax.swing.JTextArea taInfoFuncionario;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNomeEvento;
    private javax.swing.JTextField tfNomeGasto;
    private javax.swing.JTextField tfValorGasto;
    private javax.swing.JTextField tfVolPFBairro;
    private javax.swing.JTextField tfVolPFCidade;
    private javax.swing.JTextField tfVolPFComplemento;
    private javax.swing.JTextField tfVolPFNome;
    private javax.swing.JTextField tfVolPFNumero;
    private javax.swing.JTextField tfVolPFRua;
    private javax.swing.JTextField tfVolPFSenha;
    private javax.swing.JTextField tfVolPFUsuario;
    private javax.swing.JTextField tfVolPJBairro;
    private javax.swing.JTextField tfVolPJCidade;
    private javax.swing.JTextField tfVolPJComplemento;
    private javax.swing.JTextField tfVolPJNome;
    private javax.swing.JTextField tfVolPJNumero;
    private javax.swing.JTextField tfVolPJRua;
    private javax.swing.JTextField tfVolPJSenha;
    private javax.swing.JTextField tfVolPJUsuario;
    private javax.swing.JTextPane tpObjetivoEvento;
    // End of variables declaration//GEN-END:variables

	
	
}
