/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author lucas
 */
public class MoraisVoluntariado extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public MoraisVoluntariado() {
        initComponents();
		resetLayers();
		loginPanel.setVisible(true);
    }
	
	public void resetLayers(){
		loginPanel.setVisible(false);
		pnFuncionario.setVisible(false);
		pnCdVol.setVisible(false);
		pnFuncMain.setVisible(false);
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLogin5 = new keeptoo.KButton();
        loginPanel = new keeptoo.KGradientPanel();
        tfLogin = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        btLogin = new keeptoo.KButton();
        iconMV = new javax.swing.JLabel();
        ldMenus = new javax.swing.JLayeredPane();
        pnFuncionario = new keeptoo.KGradientPanel();
        lbTituloFuncionario = new javax.swing.JLabel();
        btEntregas = new keeptoo.KButton();
        btCadastroVoluntario = new keeptoo.KButton();
        btFuncLogout = new keeptoo.KButton();
        btCadastroEvento = new keeptoo.KButton();
        btCadastroTrabalho = new keeptoo.KButton();
        btAceitarDoacao = new keeptoo.KButton();
        btRemoverVoluntario = new keeptoo.KButton();
        btRelatorios = new keeptoo.KButton();
        btImportarDados = new keeptoo.KButton();
        ldFuncionario = new javax.swing.JLayeredPane();
        pnFuncMain = new javax.swing.JPanel();
        pnMainTitle = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnCdVol = new javax.swing.JPanel();
        pnCdVolTitle = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        btLogin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/new work.png"))); // NOI18N
        btLogin5.setText("Cadastrar Trabalho");
        btLogin5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLogin5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLogin5.setIconTextGap(0);
        btLogin5.setkBorderRadius(0);
        btLogin5.setkEndColor(new java.awt.Color(233, 193, 253));
        btLogin5.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btLogin5.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btLogin5.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btLogin5.setkPressedColor(new java.awt.Color(250, 209, 254));
        btLogin5.setkStartColor(new java.awt.Color(199, 96, 230));
        btLogin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Morais Voluntariado");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setkEndColor(new java.awt.Color(51, 0, 102));
        loginPanel.setkGradientFocus(90);
        loginPanel.setkStartColor(new java.awt.Color(54, 33, 89));
        loginPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        loginPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        loginPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfLogin.setBackground(new Color(0,0,0,0));
        tfLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfLogin.setForeground(new java.awt.Color(255, 255, 255));
        tfLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        tfLogin.setCaretColor(new java.awt.Color(54, 33, 89));
        tfLogin.setOpaque(false);
        tfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoginActionPerformed(evt);
            }
        });
        loginPanel.add(tfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 242, 200, 30));

        pfSenha.setBackground(new Color(0,0,0,0));
        pfSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfSenha.setForeground(new java.awt.Color(255, 255, 255));
        pfSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pfSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pfSenha.setCaretColor(new java.awt.Color(54, 33, 89));
        pfSenha.setOpaque(false);
        loginPanel.add(pfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 316, 200, 30));

        lbLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbLogin.setText("Login");
        loginPanel.add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 212, -1, -1));

        lbSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbSenha.setText("Senha");
        loginPanel.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        btLogin.setText("Entrar");
        btLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btLogin.setkEndColor(new java.awt.Color(233, 193, 253));
        btLogin.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btLogin.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btLogin.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btLogin.setkPressedColor(new java.awt.Color(250, 209, 254));
        btLogin.setkStartColor(new java.awt.Color(199, 96, 230));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        loginPanel.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 364, 112, 32));

        iconMV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logotext.png"))); // NOI18N
        loginPanel.add(iconMV, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 11, -1, -1));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ldMenus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnFuncionario.setkBorderRadius(0);
        pnFuncionario.setkEndColor(new java.awt.Color(102, 0, 102));
        pnFuncionario.setkStartColor(new java.awt.Color(51, 0, 102));
        pnFuncionario.setPreferredSize(new java.awt.Dimension(160, 500));
        pnFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloFuncionario.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lbTituloFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloFuncionario.setText("Funcionário");
        pnFuncionario.add(lbTituloFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/delivery.png"))); // NOI18N
        btEntregas.setText("Gerenciar Entregas");
        btEntregas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEntregas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEntregas.setIconTextGap(0);
        btEntregas.setkBorderRadius(0);
        btEntregas.setkEndColor(new java.awt.Color(233, 193, 253));
        btEntregas.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btEntregas.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btEntregas.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btEntregas.setkPressedColor(new java.awt.Color(250, 209, 254));
        btEntregas.setkStartColor(new java.awt.Color(199, 96, 230));
        btEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntregasActionPerformed(evt);
            }
        });
        pnFuncionario.add(btEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 160, 40));

        btCadastroVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/addfuncionario.png"))); // NOI18N
        btCadastroVoluntario.setText("Cadastrar Voluntário");
        btCadastroVoluntario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastroVoluntario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastroVoluntario.setIconTextGap(1);
        btCadastroVoluntario.setkBorderRadius(0);
        btCadastroVoluntario.setkEndColor(new java.awt.Color(233, 193, 253));
        btCadastroVoluntario.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btCadastroVoluntario.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btCadastroVoluntario.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btCadastroVoluntario.setkPressedColor(new java.awt.Color(250, 209, 254));
        btCadastroVoluntario.setkStartColor(new java.awt.Color(199, 96, 230));
        btCadastroVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroVoluntarioActionPerformed(evt);
            }
        });
        pnFuncionario.add(btCadastroVoluntario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        btFuncLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/exit.png"))); // NOI18N
        btFuncLogout.setText("Desconectar");
        btFuncLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFuncLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFuncLogout.setIconTextGap(0);
        btFuncLogout.setkBorderRadius(0);
        btFuncLogout.setkEndColor(new java.awt.Color(233, 193, 253));
        btFuncLogout.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btFuncLogout.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btFuncLogout.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btFuncLogout.setkPressedColor(new java.awt.Color(250, 209, 254));
        btFuncLogout.setkStartColor(new java.awt.Color(199, 96, 230));
        btFuncLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncLogoutActionPerformed(evt);
            }
        });
        pnFuncionario.add(btFuncLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 160, 40));

        btCadastroEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/new event.png"))); // NOI18N
        btCadastroEvento.setText("Cadastrar Evento");
        btCadastroEvento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastroEvento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastroEvento.setIconTextGap(0);
        btCadastroEvento.setkBorderRadius(0);
        btCadastroEvento.setkEndColor(new java.awt.Color(233, 193, 253));
        btCadastroEvento.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btCadastroEvento.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btCadastroEvento.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btCadastroEvento.setkPressedColor(new java.awt.Color(250, 209, 254));
        btCadastroEvento.setkStartColor(new java.awt.Color(199, 96, 230));
        btCadastroEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroEventoActionPerformed(evt);
            }
        });
        pnFuncionario.add(btCadastroEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 40));

        btCadastroTrabalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/new work.png"))); // NOI18N
        btCadastroTrabalho.setText("Cadastrar Trabalho");
        btCadastroTrabalho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastroTrabalho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastroTrabalho.setIconTextGap(0);
        btCadastroTrabalho.setkBorderRadius(0);
        btCadastroTrabalho.setkEndColor(new java.awt.Color(233, 193, 253));
        btCadastroTrabalho.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btCadastroTrabalho.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btCadastroTrabalho.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btCadastroTrabalho.setkPressedColor(new java.awt.Color(250, 209, 254));
        btCadastroTrabalho.setkStartColor(new java.awt.Color(199, 96, 230));
        btCadastroTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroTrabalhoActionPerformed(evt);
            }
        });
        pnFuncionario.add(btCadastroTrabalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 40));

        btAceitarDoacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/donate.png"))); // NOI18N
        btAceitarDoacao.setText("Aceitar Doações");
        btAceitarDoacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAceitarDoacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAceitarDoacao.setIconTextGap(0);
        btAceitarDoacao.setkBorderRadius(0);
        btAceitarDoacao.setkEndColor(new java.awt.Color(233, 193, 253));
        btAceitarDoacao.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btAceitarDoacao.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btAceitarDoacao.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btAceitarDoacao.setkPressedColor(new java.awt.Color(250, 209, 254));
        btAceitarDoacao.setkStartColor(new java.awt.Color(199, 96, 230));
        btAceitarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceitarDoacaoActionPerformed(evt);
            }
        });
        pnFuncionario.add(btAceitarDoacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 40));

        btRemoverVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/removefuncionario.png"))); // NOI18N
        btRemoverVoluntario.setText("Remover Volutário");
        btRemoverVoluntario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btRemoverVoluntario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRemoverVoluntario.setIconTextGap(0);
        btRemoverVoluntario.setkBorderRadius(0);
        btRemoverVoluntario.setkEndColor(new java.awt.Color(233, 193, 253));
        btRemoverVoluntario.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btRemoverVoluntario.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btRemoverVoluntario.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btRemoverVoluntario.setkPressedColor(new java.awt.Color(250, 209, 254));
        btRemoverVoluntario.setkStartColor(new java.awt.Color(199, 96, 230));
        btRemoverVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverVoluntarioActionPerformed(evt);
            }
        });
        pnFuncionario.add(btRemoverVoluntario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 160, 40));

        btRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/archive.png"))); // NOI18N
        btRelatorios.setText("Relatórios");
        btRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRelatorios.setIconTextGap(0);
        btRelatorios.setkBorderRadius(0);
        btRelatorios.setkEndColor(new java.awt.Color(233, 193, 253));
        btRelatorios.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btRelatorios.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btRelatorios.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btRelatorios.setkPressedColor(new java.awt.Color(250, 209, 254));
        btRelatorios.setkStartColor(new java.awt.Color(199, 96, 230));
        btRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatoriosActionPerformed(evt);
            }
        });
        pnFuncionario.add(btRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 160, 40));

        btImportarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/import.png"))); // NOI18N
        btImportarDados.setText("Importar Dados");
        btImportarDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btImportarDados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImportarDados.setIconTextGap(0);
        btImportarDados.setkBorderRadius(0);
        btImportarDados.setkEndColor(new java.awt.Color(233, 193, 253));
        btImportarDados.setkHoverEndColor(new java.awt.Color(236, 174, 243));
        btImportarDados.setkHoverForeGround(new java.awt.Color(153, 0, 255));
        btImportarDados.setkHoverStartColor(new java.awt.Color(221, 143, 253));
        btImportarDados.setkPressedColor(new java.awt.Color(250, 209, 254));
        btImportarDados.setkStartColor(new java.awt.Color(199, 96, 230));
        btImportarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImportarDadosActionPerformed(evt);
            }
        });
        pnFuncionario.add(btImportarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 160, 40));

        ldMenus.add(pnFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(ldMenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 500));

        ldFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnFuncMain.setBackground(new java.awt.Color(204, 204, 204));
        pnFuncMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMainTitle.setkBorderRadius(0);
        pnMainTitle.setkEndColor(new java.awt.Color(204, 0, 204));
        pnMainTitle.setkStartColor(new java.awt.Color(51, 0, 102));
        pnMainTitle.setPreferredSize(new java.awt.Dimension(640, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Início");

        javax.swing.GroupLayout pnMainTitleLayout = new javax.swing.GroupLayout(pnMainTitle);
        pnMainTitle.setLayout(pnMainTitleLayout);
        pnMainTitleLayout.setHorizontalGroup(
            pnMainTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainTitleLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel2)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        pnMainTitleLayout.setVerticalGroup(
            pnMainTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pnFuncMain.add(pnMainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seus dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        pnFuncMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 620, 440));

        ldFuncionario.add(pnFuncMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pnCdVol.setBackground(new java.awt.Color(204, 204, 204));
        pnCdVol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnCdVolTitle.setkBorderRadius(0);
        pnCdVolTitle.setkEndColor(new java.awt.Color(204, 0, 204));
        pnCdVolTitle.setkStartColor(new java.awt.Color(51, 0, 102));
        pnCdVolTitle.setPreferredSize(new java.awt.Dimension(640, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Voluntário");

        javax.swing.GroupLayout pnCdVolTitleLayout = new javax.swing.GroupLayout(pnCdVolTitle);
        pnCdVolTitle.setLayout(pnCdVolTitleLayout);
        pnCdVolTitleLayout.setHorizontalGroup(
            pnCdVolTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCdVolTitleLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        pnCdVolTitleLayout.setVerticalGroup(
            pnCdVolTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCdVolTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnCdVol.add(pnCdVolTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        pnCdVol.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 620, 440));

        ldFuncionario.add(pnCdVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(ldFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoginActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        resetLayers();
		loginPanel.setVisible(false);
		pnFuncionario.setVisible(true);
		pnCdVol.setVisible(true);
    }//GEN-LAST:event_btLoginActionPerformed

    private void btEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntregasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEntregasActionPerformed

    private void btCadastroVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroVoluntarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastroVoluntarioActionPerformed

    private void btFuncLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFuncLogoutActionPerformed

    private void btCadastroEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastroEventoActionPerformed

    private void btLogin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogin5ActionPerformed

    private void btCadastroTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastroTrabalhoActionPerformed

    private void btAceitarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceitarDoacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAceitarDoacaoActionPerformed

    private void btRemoverVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverVoluntarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRemoverVoluntarioActionPerformed

    private void btRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRelatoriosActionPerformed

    private void btImportarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImportarDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btImportarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoraisVoluntariado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoraisVoluntariado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoraisVoluntariado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoraisVoluntariado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoraisVoluntariado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btAceitarDoacao;
    private keeptoo.KButton btCadastroEvento;
    private keeptoo.KButton btCadastroTrabalho;
    private keeptoo.KButton btCadastroVoluntario;
    private keeptoo.KButton btEntregas;
    private keeptoo.KButton btFuncLogout;
    private keeptoo.KButton btImportarDados;
    private keeptoo.KButton btLogin;
    private keeptoo.KButton btLogin5;
    private keeptoo.KButton btRelatorios;
    private keeptoo.KButton btRemoverVoluntario;
    private javax.swing.JLabel iconMV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTituloFuncionario;
    private javax.swing.JLayeredPane ldFuncionario;
    private javax.swing.JLayeredPane ldMenus;
    private keeptoo.KGradientPanel loginPanel;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPanel pnCdVol;
    private keeptoo.KGradientPanel pnCdVolTitle;
    private javax.swing.JPanel pnFuncMain;
    private keeptoo.KGradientPanel pnFuncionario;
    private keeptoo.KGradientPanel pnMainTitle;
    private javax.swing.JTextField tfLogin;
    // End of variables declaration//GEN-END:variables
}
